<a href="https://colab.research.google.com/github/Sophie-melon/Medlytics_2026/blob/main/Challenge_Project_STUDENT_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Challenge Project
### Lyle Lalunio
---
Hypothyroidism, also called underactive thyroid or low thyroid, is a disorder of the endocrine system in which the thyroid gland does not produce enough thyroid hormone. It can cause a number of symptoms, such as poor ability to tolerate cold, a feeling of tiredness, constipation, depression, and weight gain. Occasionally there may be swelling of the front part of the neck due to goitre. Untreated hypothyroidism during pregnancy can lead to delays in growth and intellectual development in the baby or cretinism.

Worldwide, too little iodine in the diet is the most common cause of hypothyroidism. In countries with enough iodine in the diet, the most common cause of hypothyroidism is the autoimmune condition Hashimoto's thyroiditis. Less common causes include: previous treatment with radioactive iodine, injury to the hypothalamus or the anterior pituitary gland, certain medications, a lack of a functioning thyroid at birth, or previous thyroid surgery. The diagnosis of hypothyroidism, when suspected, can be confirmed with blood tests measuring thyroid-stimulating hormone (TSH) and thyroxine levels.

Worldwide about one billion people are estimated to be iodine deficient; however, it is unknown how often this results in hypothyroidism. In the United States, hypothyroidism occurs in 0.3–0.4% of people.

And that is why we iodize salt.

![alt text](https://www.mayoclinic.org/-/media/kcms/gbs/patient-consumer/images/2013/11/15/17/39/ds00181_-ds00344_-ds00353_-ds00491_-ds00492_-ds00567_-ds00660_-my00709_im01872_thyroid_gif.jpg)

Background: Doctors all around the world need our help to predict whether a patient has hypothyroid disease. We have already overspent our budget to collect such complete data on about 30 attributes for 2800 patients--a good starting number, but a larger sample would certainly be preferred. Moving forward, however, we simply cannot afford to spend so much money on data collection. Therefore, we also need to determine which attributes are the most meaningful to the predictive models, and cut out the rest that don't contribute much.

The boss wants to see a **balanced** model that can predict with a **high sensitivity** and **high specificity** while using a ***low amount of features***. Collecting complete data such as this is very rare, very time-consuming, and often very expensive. By minimizing the number of features, it will optimize future data collection by deciding what needs to be collected, and what doesn't.

## Loading the data

Let's read the data into a Pandas dataframe and look at the first 20 records.

In [3]:
import pandas as pd
### Your code here
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import roc_curve, auc
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

url = "https://raw.githubusercontent.com/MedlyticsUniversal/Data/main/Week1/allhypo.test.csv"

dataset = pd.read_csv(url)

dataset.head(20)

,Age,Sex,On Thyroxine,Query on Thyroxine,On Antithyroid Medication,Sick,Pregnant,Thyroid Surgery,I131 Treatment,Query Hypothyroid,...,T3,TT4 Measured,TT4,T4U Measured,T4U,FTI Measured,FTI,TBG Measured,TBG,Referral Source
0,35,F,f,f,f,f,f,f,f,f,...,?,f,?,f,?,f,?,f,?,other
1,63,M,f,f,f,f,f,f,f,f,...,2.5,t,108,t,0.96,t,113,f,?,SVI
2,25,F,f,f,f,f,f,f,f,f,...,2.4,t,61,t,0.82,t,75,f,?,SVHD
3,53,F,f,f,f,f,f,f,f,t,...,2.1,t,145,t,1.03,t,141,f,?,other
4,92,F,f,f,f,f,f,f,f,f,...,1.3,t,120,t,0.84,t,143,f,?,SVI
5,67,M,f,f,f,f,f,f,f,t,...,?,t,84,t,0.83,t,101,f,?,other
6,60,F,f,f,f,f,f,f,f,f,...,2.6,t,117,t,1.31,t,90,f,?,other
7,60,F,f,f,f,f,f,f,f,f,...,1.8,t,65,t,0.99,t,66,f,?,SVI
8,48,F,f,f,f,f,f,f,f,f,...,?,t,112,t,0.92,t,121,f,?,other
9,27,F,f,f,f,f,f,f,f,f,...,2.2,t,94,t,0.89,t,106,f,?,SVI
10,73,F,f,f,f,f,f,f,f,f,...,1.2,t,95,t,1.11,t,85,f,?,SVI
11,19,M,f,f,f,f,f,f,f,f,...,2.8,t,131,t,0.95,t,138,f,?,SVHC
12,72,F,f,f,f,f,f,f,f,t,...,?,t,131,t,0.5,t,265,f,?,other
13,16,M,f,f,f,f,f,f,f,f,...,?,f,?,f,?,f,?,f,?,other
14,54,F,f,f,f,f,f,f,f,f,...,3.4,t,105,f,?,f,?,f,?,other
15,39,F,t,f,f,f,f,f,f,f,...,2.4,t,148,t,1.07,t,138,f,?,other
16,38,?,f,f,f,f,f,f,f,f,...,2.2,t,145,t,1.23,t,118,f,?,SVHC
17,33,F,f,f,f,f,f,f,f,f,...,?,f,?,f,?,f,?,f,?,other
18,45,F,f,f,f,f,f,f,f,f,...,1.4,t,108,t,1.08,t,100,f,?,SVI
19,54,F,f,f,f,f,f,f,f,f,...,1.7,t,81,t,0.87,t,94,f,?,other

Great, looks like the data loaded in properly. Let's continue looking at some summary statistics on our data.

## Viewing summary statistics
The functions describe() and info() are your friends

In [4]:
dataset.describe()

              Age
count  972.000000
mean    51.423868
std     18.966700
min      7.000000
25%     35.000000
50%     54.000000
75%     67.000000
max     93.000000

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 972 entries, 0 to 971
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        972 non-null    int64
 1   Sex                        972 non-null    object
 2   On Thyroxine               972 non-null    object
 3   Query on Thyroxine         972 non-null    object
 4   On Antithyroid Medication  972 non-null    object
 5   Sick                       972 non-null    object
 6   Pregnant                   972 non-null    object
 7   Thyroid Surgery            972 non-null    object
 8   I131 Treatment             972 non-null    object
 9   Query Hypothyroid          972 non-null    object
 10  Query Hyperthyroid         972 non-null    object
 11  Lithium                    972 non-null    object
 12  Goiter                     972 non-null    object
 13  Tumor                      972 non-null    object
 14  Hypopituitary              972 non-null    object
 15  Psych                      972 non-null    object
 16  TSH Measured               972 non-null    object
 17  TSH                        972 non-null    object
 18  T3 Measured                972 non-null    object
 19  T3                         972 non-null    object
 20  TT4 Measured               972 non-null    object
 21  TT4                        972 non-null    object
 22  T4U Measured               972 non-null    object
 23  T4U                        972 non-null    object
 24  FTI Measured               972 non-null    object
 25  FTI                        972 non-null    object
 26  TBG Measured               972 non-null    object
 27  TBG                        972 non-null    object
 28  Referral Source            972 non-null    object
dtypes: int64(1), object(28)
memory usage: 220.3+ KB

Note the data types are all objects--even columns that are obviously numeric like Age.

## Data cleaning

To start, let's make all the numerical columns contain the correct type of values and change the data type of those columns to numeric. Let's also replace all those question marks with the median of the respective column.

Hint: To make it easier, first try converting all the "?" to NaN.

In [6]:
import numpy as np

### your code here
dataset.replace("?", np.nan, inplace = True)

/tmp/ipykernel_2570/2232287621.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset.replace("?", np.nan, inplace = True)

Hmm, still looks like the TBG column is unfilled, implying it was empty to begin with. Let's get rid of this column, then (and make sure to get rid of it in your list of numeric columns, too!)

In [ ]:
dataset.drop(columns = ['TBG'], inplace = True)

numeric_columns.remove('TBG')

All right, let's take a look now at the info of *just the numeric columns* in the dataset:

In [ ]:
copy[numeric_columns].info()

Perfect, now let's fix that class feature. According to the note the data collectors included with this data, the ".|####" refers to a patient number, and is not necessarily relevant for our purposes here.

In [ ]:
### Your code here

Let's run the describe() function on just the "class" column.

In [ ]:
dataset['class'].describe()

count         2800
unique           4
top       negative
freq          2580
Name: class, dtype: object

It looks like there are actually 4 unique classification variables! Thank goodness we didn't assume it was binary.

Display all the unique values in the class column.

In [ ]:
### Your code here

But let's make it binary for the sake of this example anyway. If you finish early later on, try the multiclass classifier with all 4 values!

In [ ]:
### Your code here

Before we move on, let's not forget to run the describe() function on just  your categorical columns, too.
Compare it to the describe() that your numeric columns produce.

In [ ]:
### Your code here

Great! Let's see if there's any other records we have to address. count() is a nice way to check if we have any other missing values.

In [ ]:
dataset.count()

We could replace the missing values in proportion to the current number of males and females over the total, but that is making an assumption we don't have to make. For now, let's simply cut the records of all these sexless people out of our data.

In [ ]:
### Your code here

Nice! Now we have a pretty clean dataset to work with. Let's now do some further data analysis and visualization to better understand what we're working with.

## Data analysis and visualization

Check the correlation

In [ ]:
### Your code here

Convert the class feature to numeric so we can also see the correlations it has with the numeric features, and check the correlation again.

In [ ]:
import pandas as po
### Your code here

Let's do some further visual analysis using a new module called seaborn. Explore its incredible versatility and diversity with data visualization here: https://seaborn.pydata.org/

In [ ]:
import seaborn as sns
sns.pairplot(copy)

OK! I think we're ready to create and select some supervised learning models. To get the ball rolling, select Age and Sex as our explanatory features (and class as the target feature, obviously).

## Model training and selection

Let's dummy the categorical variables (but not the class value!) and view the column names to select some for our model.

In [ ]:
### Your code here

All right, let's now split our data into training and testing in an 80-20 split. For consistency, let's all use a seed of 8675309.

In [ ]:
from sklearn.model_selection import train_test_split

## Your code here

For reusability, let's make a logistic regression function that will take our training and testing data as arguments. Inside the function, build a model on your training data, fit it with your training class data, and return a list of your predictions.

In [ ]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression

def log_reg(train_X,train_Y,test_X,test_Y):

  ### Your code here

Fantastic, we have just built a logistic regression model! Let's go see how well it performs.

### Model evaluation

To start, let's establish the baseline performance. This is important because it provides a starting point of comparison for later evaluation methods, like accuracy.

A good baseline model to use is the Zero Rule algorithm. In classification problems, it simply predicts the class value with the greatest number of instances every time.

In [ ]:
def zero_rule_algorithm_classification(train,test):
  ## Your code here

Get your baseline performance by calculating the accuracy of your Zero Rule algorithm.

In [ ]:
## Your code here

So maybe accuracy isn't the best performance measure for this dataset. As you've seen already, even when the models predict "negative" for all the records, we could already achieve a ~92% accuracy. However, that also implies we incorrectly predicted 100% of the positive cases, which in the context of this problem, is fatal.

Thankfully, it isn't the only way to evaluate your model. Let's take a look at a confusion matrix.

![alt text](https://i.imgur.com/uipmEwt.png)

Create a confusion matrix using the logistic regression function you built earlier.

In [ ]:
from sklearn.metrics import confusion_matrix
### Your code here


Yet another appropriate metric is the Area Under the Receiver Operator Curve. Specifically, the diagnostic performance of a test, or the accuracy of a test to discriminate diseased cases from normal cases is evaluated using Receiver Operating Characteristic (ROC) curve analysis.

When you consider the results of a particular test in two populations, one population with a disease, the other population without the disease, you will rarely observe a perfect separation between the two groups. Hence, the overlapping areas in the diagram below (FN, FP).

In a Receiver Operating Characteristic (ROC) curve the true positive rate (Sensitivity) is plotted in function of the false positive rate (100-Specificity) for different cut-off points. Each point on the ROC curve represents a sensitivity/specificity pair corresponding to a particular decision threshold. A test with perfect discrimination (no overlap in the two distributions) has a ROC curve that passes through the upper left corner (100% sensitivity, 100% specificity). Therefore the closer the ROC curve is to the upper left corner, the higher the overall accuracy of the test.

![alt text](https://www.medcalc.org/manual/_help/images/roc_intro1.png)

Now, to graph the AUROC curve, we will need to predict probabilities of choosing a specific class value rather than the class value itself. Make a new logistic regression model that does so.

In [ ]:
from sklearn.linear_model import LogisticRegression

### Your code here

Now calculate the area under the receiver operator curve with your predictions.

In [ ]:
from sklearn import metrics

### Your code here

Now graph the ROC curve using matplotlib, fully labeled.

In [ ]:
import matplotlib.pyplot as plt
### Your code here

In conclusion, it looks like this model performed pretty bad. It's probably best to try out different columns or perhaps use a different model before we submit our model for scoring.

# Submitting your Model

Once you believe to have found the best classifier, run your classifier on the test images and make a pickle file containing of your predictions contained a pandas dataframe.

This pandas dataframe will contain three columns for your binary classifier (or 5 columns for the multiclass classifier): the first column should be your model's "best guess" for each patient (either 0 or 1, negative or positive) and the last two columns should be the probability the patient would be classified as either a 0 or 1.

(see below for reference)

In [ ]:
#pickling example
import pickle
predictions=po.DataFrame({"guesses":[0,1,0,1],"prob_neg":[.75,.15,.63,.20],"prob_pos":[.25,.85,.27,.80]})
prediction_pickle_path = 'prediction_pickle.pkl'

from google.colab import files
# Create an variable to pickle and open it in write mode
prediction_pickle = open(prediction_pickle_path, 'wb')
pickle.dump(predictions, prediction_pickle)
files.download(prediction_pickle_path)
prediction_pickle.close()

In [ ]:
prediction_unpickle = open(prediction_pickle_path, 'rb')

# load the unpickle object into a variable
predictions = pickle.load(prediction_unpickle)

print(predictions)

   guesses  prob_neg  prob_pos
0        0      0.75      0.25
1        1      0.15      0.85
2        0      0.63      0.27
3        1      0.20      0.80

# Scoring your Model

**Confusion Matrix**: You will receive a certain number of points for each correct classification and a certain point penalty for each incorrect classification. The points are weighted, and are designed to equate to 0 in a Zero Rule baseline model. This point scheme is designed to punish you heavily for predicting false positives (FP) and false negatives (FN)--FN cases especially. In doing so, we hope you see the importance of clinical considerations and treat your models from a more human perspective, rather than detached from it.

**Area Under ROC Curve**: A receiver operating characteristic (ROC) curve plots the true positive rate (y) against the false positive rate (x) at many decision threshold settings (output < threshold = 0, output > threshold = 1). The area under this curve represents the probability that a classifier will rank a randomly chosen positive instance higher than a randomly chosen negative one.

**Real World Cost**: Similar to the confusion matrix, we want you to keep in mind the other aspects of healthcare analytics--in this case, economic feasibility. In essence, we want you to minimize the amount of time and money spent on data collection by reducing the number of features collected. Each record certainly required a lot of time and money from several individuals and businesses to reliably create, and we hope you gain a better understanding of conducting a useful cost-benefit analysis with this scoring method. The full details of the weighted features can be found in the GitHub.

# Moving to the Next Level

For those that finish early, remember how I converted the class values into simply "negative" and "positive"? Now try tackling the multiclass classifier (predicting the different types of positive hypothyroid cases instead of simply negative or positive)!

The same rules apply!

(And for those that also finish the multiclass classifer, see Lyle for further instructions).